# Generated by Django 5.2.1 on 2025-06-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_telegramalertreceiver_delete_receiverprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramalertreceiver',
            old_name='can_receive_alerts',
            new_name='receive_notifications',
        ),
        migrations.RemoveField(
            model_name='telegramalertreceiver',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='telegramalertreceiver',
            name='telegram_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
