# Generated by Django 5.2.1 on 2025-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_can_receive_alerts_telegramalertreceiver_receive_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramalertreceiver',
            name='telegram_number',
        ),
        migrations.AddField(
            model_name='telegramalertreceiver',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
